# Generated by Django 5.1.1 on 2024-10-04 11:14

import imagekit.models.fields
import market.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image_urls",
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default="default/no_image.jpg", upload_to=market.models.upload_to
            ),
            preserve_default=False,
        ),
    ]
