# Generated by Django 5.0.8 on 2024-10-08 01:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_remove_productimage_image_urls_productimage_image"),
    ]
    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
