# Generated by Django 5.1.1 on 2024-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_product_user_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_urls",
            field=models.ImageField(upload_to="media/products/"),
        ),
    ]
