# Generated by Django 5.0.8 on 2024-10-09 00:32
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insta", "0002_alter_comment_options_alter_like_options_and_more"),
    ]
    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="insta/"),
        ),
    ]
