# Generated by Django 5.1.2 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insta", "0003_alter_postimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="image",
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_url",
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
