# Generated by Django 5.1.2 on 2024-10-14 19:04

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insta", "0004_remove_postimage_image_postimage_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="postimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default=1, upload_to="insta/"
            ),
            preserve_default=False,
        ),
    ]
