# Generated by Django 5.1.1 on 2024-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatroom_room_key_alter_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/chat_images/"
            ),
        ),
    ]
