# Generated by Django 5.1.1 on 2024-10-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longitude",
        ),
    ]
