# Generated by Django 5.0.8 on 2024-10-07 02:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_user_nickname_alter_user_email_and_more"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="user",
            name="temperature",
        ),
    ]
