# Generated by Django 5.1.2 on 2024-10-12 15:32

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="profile_images/"
            ),
        ),
    ]
